// Auto-generated by AiWebAppBuilder — do not edit.
// Lightweight PostgREST client. Talks to a dedicated, isolated database schema.
// PostgREST query syntax: https://postgrest.org/en/stable/references/api/tables_views.html
//   db.select('todos', '?completed=eq.false&order=created_at.desc')
//   db.insert('todos', { title: 'Buy milk' })
//   db.update('todos', '?id=eq.1', { completed: true })
//   db.remove('todos', '?id=eq.1')
//   db.rpc('admin_login', { p_username: 'owner', p_password: '...' })

const BASE_URL = import.meta.env.VITE_POSTGREST_URL as string;
const SCHEMA = import.meta.env.VITE_DB_SCHEMA as string;
const ANON_TOKEN = import.meta.env.VITE_DB_ANON_TOKEN as string;
const FILES_URL = import.meta.env.VITE_PROJECT_FILES_URL as string;

type QueryValue = string | number | boolean | null | undefined;
type QueryOptions = {
  filters?: Record<string, QueryValue>;
  orderBy?: string;
  ascending?: boolean;
  limit?: number;
  offset?: number;
};
type Query = string | QueryOptions | Record<string, QueryValue>;
let adminSessionToken = '';

/**
 * Uses an application-issued bearer token for subsequent database requests.
 * Passing null clears the active session. Persistence remains the application's
 * responsibility so each generated app can choose its own session lifetime.
 */
export function setAdminSession(token: string | null | undefined): void {
  adminSessionToken = typeof token === 'string' ? token.trim() : '';
}

export function clearAdminSession(): void {
  adminSessionToken = '';
}

function queryString(query: Query = ''): string {
  if (typeof query === 'string')
    return query && !query.startsWith('?') ? `?${query}` : query;
  const options = query as QueryOptions;
  const hasOptions = options.filters !== undefined
    || options.orderBy !== undefined
    || options.ascending !== undefined
    || options.limit !== undefined
    || options.offset !== undefined;
  const entries: Array<[string, QueryValue]> = hasOptions
    ? [
        ...Object.entries(options.filters ?? {}).map(([key, item]) => [key, item] as [string, QueryValue]),
        ...(options.orderBy
          ? [['order', `${options.orderBy}.${options.ascending === false ? 'desc' : 'asc'}`] as [string, QueryValue]]
          : []),
        ...(options.limit !== undefined ? [['limit', options.limit] as [string, QueryValue]] : []),
        ...(options.offset !== undefined ? [['offset', options.offset] as [string, QueryValue]] : []),
      ]
    : Object.entries(query as Record<string, QueryValue>);
  const value = entries
    .filter(([, item]) => item !== undefined)
    .map(([key, item]) => {
      const raw = String(item ?? '');
      const encoded = key === 'order' || /^(eq|neq|gt|gte|lt|lte|like|ilike|in|is|not)\./.test(raw)
        ? raw
        : `eq.${raw}`;
      return `${encodeURIComponent(key)}=${encodeURIComponent(encoded)}`;
    })
    .join('&');
  return value ? `?${value}` : '';
}

function buildHeaders(write: boolean): Record<string, string> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    'Accept-Profile': SCHEMA,
  };
  if (write) headers['Content-Profile'] = SCHEMA;
  const bearerToken = adminSessionToken || ANON_TOKEN;
  if (bearerToken) headers['Authorization'] = `Bearer ${bearerToken}`;
  return headers;
}

async function handle<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`PostgREST ${res.status}: ${text}`);
  }
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  return (text ? JSON.parse(text) : undefined) as T;
}

export const db = {
  /** Read rows. `query` is an optional PostgREST query string starting with '?'. */
  async select<T = any>(table: string, query: Query = ''): Promise<T[]> {
    const res = await fetch(`${BASE_URL}/${table}${queryString(query)}`, { headers: buildHeaders(false) });
    return handle<T[]>(res);
  },
  /** Insert one row or an array of rows. Returns the inserted rows. */
  async insert<T = any>(table: string, values: unknown): Promise<T[]> {
    const res = await fetch(`${BASE_URL}/${table}`, {
      method: 'POST',
      headers: { ...buildHeaders(true), Prefer: 'return=representation' },
      body: JSON.stringify(values),
    });
    return handle<T[]>(res);
  },
  /**
   * Update rows matched by `query`. Returns the updated rows.
   * `id` and `created_at` are stripped from `values` automatically — every table's
   * schema defines these as identity/DEFAULT columns, and Postgres rejects a PATCH
   * that tries to set them to anything else. Passing the full row object (as returned
   * by a previous `select`) is safe; you don't need to omit these fields yourself.
   */
  async update<T = any>(table: string, query: Query, values: unknown): Promise<T[]> {
    const { id: _id, created_at: _createdAt, ...rest } = (values ?? {}) as Record<string, unknown>;
    const res = await fetch(`${BASE_URL}/${table}${queryString(query)}`, {
      method: 'PATCH',
      headers: { ...buildHeaders(true), Prefer: 'return=representation' },
      body: JSON.stringify(rest),
    });
    return handle<T[]>(res);
  },
  /** Delete rows matched by `query`. */
  async remove(table: string, query: Query): Promise<void> {
    const res = await fetch(`${BASE_URL}/${table}${queryString(query)}`, {
      method: 'DELETE',
      headers: buildHeaders(true),
    });
    await handle<void>(res);
  },
  /** Call a PostgreSQL function exposed by PostgREST. */
  async rpc<T = any>(functionName: string, args: Record<string, unknown> = {}): Promise<T[]> {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(functionName))
      throw new Error('Invalid database function name.');
    const res = await fetch(`${BASE_URL}/rpc/${encodeURIComponent(functionName)}`, {
      method: 'POST',
      headers: { ...buildHeaders(true), Prefer: 'return=representation' },
      body: JSON.stringify(args),
    });
    return handle<T[]>(res);
  },
  // Keep method-style session calls working for older generated projects.
  setAdminSession,
  clearAdminSession,
};

// Keep a default export for compatibility with existing generated applications.
// New prompts use `import { db }`, but older projects may already contain
// `import db` and must continue to compile when the platform refreshes this file.
export default db;

export type ProjectFile = {
  id: string;
  name: string;
  contentType: string;
  size: number;
  url: string;
};

/** Uploads private files through Humainum. Persist the returned metadata with `db`. */
export const storage = {
  async upload(file: File, _path?: string): Promise<ProjectFile> {
    if (!FILES_URL) throw new Error('Project file storage is not configured.');
    const body = new FormData();
    body.append('file', file, file.name);
    const res = await fetch(FILES_URL, { method: 'POST', body });
    return handle<ProjectFile>(res);
  },
  async remove(fileId: string): Promise<void> {
    if (!FILES_URL) throw new Error('Project file storage is not configured.');
    const res = await fetch(`${FILES_URL}/${encodeURIComponent(fileId)}`, { method: 'DELETE' });
    await handle<void>(res);
  },
};

export type Db = typeof db;