export type Language = 'tr' | 'en' | 'ar'

export const languages: Array<{ code: Language; label: string; nativeLabel: string }> = [
  { code: 'tr', label: 'Türkçe', nativeLabel: 'TR' },
  { code: 'en', label: 'English', nativeLabel: 'EN' },
  { code: 'ar', label: 'العربية', nativeLabel: 'AR' },
]

type ServiceCopy = { title: string; text: string }
type FleetCopy = { meta: string; equipment: string; alt: string }

const copy = {
  tr: {
    nav: { services: 'Hizmetler', fleet: 'Filo', corporate: 'Kurumsal', about: 'Hakkımızda', faq: 'SSS', contact: 'İletişim', booking: 'Rezervasyon' },
    actions: { quote: 'Teklif al', plan: 'Transfer planla', explore: 'Hizmetleri keşfet', start: 'Rezervasyon başlat', call: 'Ara', whatsapp: 'WhatsApp', route: 'Güzergâhı planla', send: 'Mesaj gönder' },
    labels: { language: 'Dil seçimi', home: 'VIP Transfer ana sayfa', menuOpen: 'Menüyü aç', menuClose: 'Menüyü kapat', from: 'Nereden', to: 'Nereye', service: 'Hizmet tipi', name: 'Ad soyad', email: 'E-posta', message: 'Mesajınız' },
    home: { eyebrow: 'KATAR · ÖZEL ŞOFÖRLÜ ULAŞIM', title: <>Vardığınız andan itibaren, <em>ayrıcalıklı</em> bir yolculuk.</>, intro: 'Havalimanından otele, toplantıdan özel davete. Zamanınıza saygı duyan, konforu standart kabul eden VIP transfer hizmeti.', airport: 'Havalimanı transferi', rental: 'Şoförlü VIP kiralama', corporate: 'Kurumsal transfer', origin: 'Kalkış bölgesi', destination: 'Varış bölgesi', trust: ['Güvenli ve deneyimli şoförler', 'Zamanında karşılama', 'Özenli, kişisel hizmet'], servicesEyebrow: 'HİZMETLER', servicesTitle: <>Yolculuğunuzun<br /><em>ritmine</em> uyum.</>, servicesText: 'İş veya seyahat için Katar’da olduğunuzda, tüm detayları sizin yerinize düşünürüz.', fleetEyebrow: 'FİLO', fleetTitle: <>Konforun<br /><em>doğru</em> karşılığı.</>, fleetText: 'Her araç, konfor ve güvenlik beklentilerinizi karşılamak için seçildi.', whyEyebrow: 'NEDEN BİZ', whyTitle: <>Sadece bir araç değil, <em>iyi hissettiren</em> bir hizmet.</>, bookingEyebrow: 'REZERVASYON', bookingTitle: <>Planınızı paylaşın,<br /><em>gerisini bize bırakın.</em></>, bookingText: 'Güzergâhınızı, aracınızı ve ihtiyaçlarınızı dört kolay adımda belirleyin.' },
    services: [
      { title: 'Havalimanı transferi', text: 'Uçuş takibi, karşılama tabelası ve cömert bekleme süresiyle terminalden itibaren sakin bir başlangıç.' },
      { title: 'Şoförlü VIP kiralama', text: 'Saatlik, günlük veya şehirler arası programlarınız için deneyimli şoför ve seçkin araç konforu.' },
      { title: 'Düğün ve özel etkinlik', text: 'Süslemeli araç, konvoy ve gelin arabası koordinasyonuyla özel gününüzün her anına özen.' },
      { title: 'Kurumsal transfer', text: 'Aylık anlaşma, faturalı operasyon ve yöneticileriniz için güvenilir, dakik ulaşım planı.' },
    ] as ServiceCopy[],
    fleet: [
      { meta: '6 yolcu · 6 bagaj', equipment: 'Geniş kabin · Wi-Fi · Su ikramı', alt: 'Executive Van lüks araç' },
      { meta: '3 yolcu · 3 bagaj', equipment: 'Deri koltuk · Klima · Gizlilik camı', alt: 'Luxury Sedan lüks araç' },
      { meta: '5 yolcu · 5 bagaj', equipment: 'Yüksek sürüş · Deri kabin · Şarj ünitesi', alt: 'Premium SUV lüks araç' },
    ] as FleetCopy[],
    pages: { services: ['HİZMETLER', <>Katar’da her plan için<br /><em>özenli ulaşım.</em></>, 'İhtiyacınıza göre tasarlanan dört hizmet başlığı; net iletişim, zamanında karşılama ve seçkin araç konforuyla.'], fleet: ['FİLO', <>Programınıza uygun<br /><em>araç.</em></>, 'Yolcu ve bagaj kapasitenize göre önerilen, özenle seçilmiş araçlar.'], corporate: ['KURUMSAL', <>İşinizin temposuna<br /><em>uyum sağlayan</em> transfer.</>, 'Aylık anlaşma, faturalı operasyon ve yönetici transferleri için tek bir güvenilir çözüm ortağı.'], about: ['HAKKIMIZDA', <>Katar’da hareketin<br /><em>daha iyi hali.</em></>, 'VIP Transfer, yolculuğu yalnızca bir noktadan diğerine gitmek değil, iyi hissettiren bir deneyim olarak görür.'], contact: ['İLETİŞİM', <>Planınızı<br /><em>konuşalım.</em></>, 'Güzergâhınızı ve ihtiyaçlarınızı paylaşın; size en uygun akışı birlikte oluşturalım.'], kvkk: ['KVKK', <>Verinizin<br /><em>güvenliği.</em></>, 'Kişisel verilerin korunması ve işlenmesine ilişkin aydınlatma metni.'], faq: ['SSS', <>Merak ettikleriniz,<br /><em>net cevaplar.</em></>, 'Rezervasyon, araç seçimi ve transfer akışı hakkında sık sorulan sorular.'], booking: ['REZERVASYON', <>Dört adımda<br /><em>transfer planı.</em></>, 'Güzergâhınızı paylaşın, aracınızı seçin ve ihtiyaçlarınızı ekleyin.'] },
    booking: { steps: ['Güzergâh', 'Araç seçimi', 'Ekstralar', 'İletişim ve onay'], details: ['Hizmet tipi, bölgeler, tarih-saat ve yolcu bilgileri.', 'Kapasitenize uygun araçları fiyatlarıyla görün.', 'Çocuk koltuğu, karşılama tabelası ve notunuzu ekleyin.', 'Bilgilerinizi ve KVKK onayınızı tamamlayın.'], selected: 'Seçili araç', start: 'Akışı başlat' },
    contact: { title: <>Doğru plan, <em>iyi başlangıç.</em></>, text: 'Güzergâhınızı paylaşın; rezervasyon akışına geçmeden önce ihtiyaçlarınızı birlikte netleştirelim.', namePlaceholder: 'Adınız ve soyadınız', emailPlaceholder: 'ornek@eposta.com', messagePlaceholder: 'Transfer planınızı kısaca anlatın' },
    faq: { questions: ['Fiyat nasıl hesaplanır?', 'Uçuşum gecikirse ne olur?', 'Hangi ödeme yöntemlerini kabul ediyorsunuz?', 'Araç seçimini nasıl yapabilirim?'], answer: 'Rezervasyon ekibimiz, güzergâh ve ihtiyaçlarınıza göre net bilgiyi teklif sürecinde paylaşır.' },
    footer: { description: 'Katar’da konforlu, güvenilir ve özenli ulaşım.', contact: 'İletişim', contactText: 'Telefon, WhatsApp ve e-posta bilgileri yakında burada yer alacak.', languages: 'DİL', privacy: 'KVKK' },
  },
  en: {
    nav: { services: 'Services', fleet: 'Fleet', corporate: 'Corporate', about: 'About us', faq: 'FAQ', contact: 'Contact', booking: 'Reservation' }, actions: { quote: 'Get a quote', plan: 'Plan your transfer', explore: 'Explore services', start: 'Start reservation', call: 'Call', whatsapp: 'WhatsApp', route: 'Plan route', send: 'Send message' }, labels: { language: 'Language selection', home: 'VIP Transfer home', menuOpen: 'Open menu', menuClose: 'Close menu', from: 'From', to: 'To', service: 'Service type', name: 'Full name', email: 'Email', message: 'Your message' },
    home: { eyebrow: 'QATAR · PRIVATE CHAUFFEURED TRANSPORT', title: <>A privileged journey, <em>from the moment</em> you arrive.</>, intro: 'From airport to hotel, meeting to special event. VIP transport that respects your time and makes comfort the standard.', airport: 'Airport transfer', rental: 'Chauffeured VIP rental', corporate: 'Corporate transfer', origin: 'Pickup zone', destination: 'Destination zone', trust: ['Safe, experienced chauffeurs', 'On-time pickup', 'Thoughtful personal service'], servicesEyebrow: 'SERVICES', servicesTitle: <>In step with<br /><em>your rhythm.</em></>, servicesText: 'When business or travel brings you to Qatar, we take care of every detail.', fleetEyebrow: 'FLEET', fleetTitle: <>The right<br /><em>kind</em> of comfort.</>, fleetText: 'Every vehicle is selected around your comfort and safety expectations.', whyEyebrow: 'WHY US', whyTitle: <>More than a vehicle, <em>a service that feels right.</em>,</>, bookingEyebrow: 'RESERVATION', bookingTitle: <>Share your plan,<br /><em>leave the rest to us.</em></>, bookingText: 'Choose your route, vehicle and needs in four simple steps.' },
    services: [{ title: 'Airport transfer', text: 'A calm start from the terminal with flight tracking, a welcome sign and generous waiting time.' }, { title: 'Chauffeured VIP rental', text: 'Experienced chauffeurs and refined comfort for hourly, daily or intercity programs.' }, { title: 'Weddings and special events', text: 'Decorated vehicles, convoys and bridal car coordination for every special moment.' }, { title: 'Corporate transfer', text: 'Monthly agreements, invoiced operations and dependable executive transport.' }] as ServiceCopy[], fleet: [{ meta: '6 passengers · 6 bags', equipment: 'Spacious cabin · Wi-Fi · Refreshments', alt: 'Luxury Executive Van' }, { meta: '3 passengers · 3 bags', equipment: 'Leather seats · Climate control · Privacy glass', alt: 'Luxury Sedan' }, { meta: '5 passengers · 5 bags', equipment: 'Elevated drive · Leather cabin · Charging', alt: 'Premium SUV' }] as FleetCopy[],
    pages: { services: ['SERVICES', <>Thoughtful transport<br /><em>for every plan.</em></>, 'Four services shaped around your needs, with clear communication, punctual pickup and refined comfort.'], fleet: ['FLEET', <>A vehicle for<br /><em>your program.</em></>, 'Carefully selected vehicles recommended for your passenger and luggage capacity.'], corporate: ['CORPORATE', <>Transport that moves<br /><em>with your business.</em></>, 'One reliable partner for monthly agreements, invoiced operations and executive transfers.'], about: ['ABOUT US', <>A better way<br /><em>to move in Qatar.</em></>, 'VIP Transfer sees travel not simply as getting from A to B, but as an experience that feels good.'], contact: ['CONTACT', <>Let’s discuss<br /><em>your plan.</em></>, 'Share your route and needs; we will shape the right journey together.'], kvkk: ['PRIVACY', <>Your data,<br /><em>protected.</em></>, 'Information about the protection and processing of personal data.'], faq: ['FAQ', <>Your questions,<br /><em>answered clearly.</em></>, 'Frequently asked questions about reservations, vehicles and transfers.'], booking: ['RESERVATION', <>Your transfer plan<br /><em>in four steps.</em></>, 'Share your route, choose a vehicle and add your requirements.'] },
    booking: { steps: ['Route', 'Vehicle selection', 'Extras', 'Contact and confirmation'], details: ['Service, zones, date, time and passenger details.', 'See vehicles matching your capacity with prices.', 'Add a child seat, welcome sign and notes.', 'Complete your details and privacy consent.'], selected: 'Selected vehicle', start: 'Start flow' }, contact: { title: <>The right plan, <em>a better start.</em></>, text: 'Share your route so we can clarify your needs before the reservation flow.', namePlaceholder: 'Your name', emailPlaceholder: 'name@example.com', messagePlaceholder: 'Briefly describe your transfer plan' }, faq: { questions: ['How is the price calculated?', 'What happens if my flight is delayed?', 'Which payment methods do you accept?', 'How do I choose a vehicle?'], answer: 'Our reservation team shares clear information based on your route and requirements during the quote process.' }, footer: { description: 'Comfortable, reliable and thoughtful transport in Qatar.', contact: 'CONTACT', contactText: 'Phone, WhatsApp and email details will be added here.', languages: 'LANGUAGE', privacy: 'Privacy' },
  },
  ar: {
    nav: { services: 'الخدمات', fleet: 'الأسطول', corporate: 'الشركات', about: 'من نحن', faq: 'الأسئلة الشائعة', contact: 'اتصل بنا', booking: 'الحجز' }, actions: { quote: 'احصل على عرض', plan: 'خطط رحلتك', explore: 'اكتشف الخدمات', start: 'ابدأ الحجز', call: 'اتصال', whatsapp: 'واتساب', route: 'خطط المسار', send: 'إرسال الرسالة' }, labels: { language: 'اختيار اللغة', home: 'الصفحة الرئيسية للنقل الفاخر', menuOpen: 'فتح القائمة', menuClose: 'إغلاق القائمة', from: 'من', to: 'إلى', service: 'نوع الخدمة', name: 'الاسم الكامل', email: 'البريد الإلكتروني', message: 'رسالتك' },
    home: { eyebrow: 'قطر · نقل خاص مع سائق', title: <>رحلة <em>استثنائية</em> منذ لحظة وصولك.</>, intro: 'من المطار إلى الفندق، ومن الاجتماع إلى المناسبة الخاصة. خدمة نقل فاخرة تحترم وقتك وتجعل الراحة معياراً.', airport: 'نقل من المطار', rental: 'تأجير فاخر مع سائق', corporate: 'نقل الشركات', origin: 'منطقة الانطلاق', destination: 'منطقة الوصول', trust: ['سائقون آمنون وذوو خبرة', 'استقبال في الموعد', 'خدمة شخصية بعناية'], servicesEyebrow: 'الخدمات', servicesTitle: <>نواكب<br /><em>إيقاع رحلتك.</em></>, servicesText: 'عندما تأتي إلى قطر للعمل أو السفر، نهتم بكل التفاصيل نيابة عنك.', fleetEyebrow: 'الأسطول', fleetTitle: <>الراحة<br /><em>المناسبة.</em></>, fleetText: 'تم اختيار كل سيارة لتلبي توقعاتك في الراحة والأمان.', whyEyebrow: 'لماذا نحن', whyTitle: <>ليست مجرد سيارة، <em>بل خدمة تشعرك بالرضا.</em></>, bookingEyebrow: 'الحجز', bookingTitle: <>شارك خطتك،<br /><em>واترك الباقي علينا.</em></>, bookingText: 'حدد مسارك وسيارتك واحتياجاتك في أربع خطوات بسيطة.' },
    services: [{ title: 'نقل من المطار', text: 'بداية هادئة من صالة الوصول مع تتبع الرحلة ولوحة استقبال ووقت انتظار مريح.' }, { title: 'تأجير فاخر مع سائق', text: 'سائقون ذوو خبرة وراحة راقية للبرامج بالساعة أو اليوم أو بين المدن.' }, { title: 'الأعراس والمناسبات الخاصة', text: 'سيارات مزينة وقوافل وتنسيق سيارة العروس لكل لحظة مميزة.' }, { title: 'نقل الشركات', text: 'اتفاقيات شهرية وعمليات بفواتير ونقل موثوق للمديرين.' }] as ServiceCopy[], fleet: [{ meta: '6 ركاب · 6 حقائب', equipment: 'مقصورة واسعة · Wi‑Fi · مرطبات', alt: 'سيارة Executive Van فاخرة' }, { meta: '3 ركاب · 3 حقائب', equipment: 'مقاعد جلدية · تكييف · زجاج خصوصية', alt: 'سيارة Luxury Sedan فاخرة' }, { meta: '5 ركاب · 5 حقائب', equipment: 'قيادة مرتفعة · مقصورة جلدية · شحن', alt: 'سيارة Premium SUV فاخرة' }] as FleetCopy[],
    pages: { services: ['الخدمات', <>نقل بعناية<br /><em>لكل خطة.</em></>, 'أربع خدمات مصممة حول احتياجاتك، مع تواصل واضح واستقبال دقيق وراحة راقية.'], fleet: ['الأسطول', <>سيارة تناسب<br /><em>برنامجك.</em></>, 'سيارات مختارة بعناية وفق عدد الركاب والحقائب.'], corporate: ['الشركات', <>نقل يواكب<br /><em>أعمالك.</em></>, 'شريك موثوق للاتفاقيات الشهرية والعمليات المفوترة ونقل المديرين.'], about: ['من نحن', <>طريقة أفضل<br /><em>للتنقل في قطر.</em></>, 'نرى الرحلة تجربة مريحة ومميزة، وليست مجرد انتقال من مكان إلى آخر.'], contact: ['اتصل بنا', <>لنتحدث عن<br /><em>خطتك.</em></>, 'شارك مسارك واحتياجاتك لنصمم الرحلة المناسبة معاً.'], kvkk: ['الخصوصية', <>بياناتك<br /><em>محمية.</em></>, 'معلومات حول حماية ومعالجة البيانات الشخصية.'], faq: ['الأسئلة الشائعة', <>أسئلتكم،<br /><em>إجابات واضحة.</em></>, 'أسئلة شائعة حول الحجز والسيارات وخدمات النقل.'], booking: ['الحجز', <>خطة نقلك<br /><em>في أربع خطوات.</em></>, 'شارك مسارك واختر السيارة وأضف متطلباتك.'] },
    booking: { steps: ['المسار', 'اختيار السيارة', 'الإضافات', 'التواصل والتأكيد'], details: ['الخدمة والمناطق والتاريخ والوقت وعدد الركاب.', 'شاهد السيارات المناسبة لسعتك مع الأسعار.', 'أضف مقعد طفل أو لوحة استقبال أو ملاحظات.', 'أكمل بياناتك ووافِق على الخصوصية.'], selected: 'السيارة المختارة', start: 'ابدأ الخطوات' }, contact: { title: <>الخطة الصحيحة، <em>بداية أفضل.</em></>, text: 'شارك مسارك لنوضح احتياجاتك قبل بدء الحجز.', namePlaceholder: 'اسمك الكامل', emailPlaceholder: 'name@example.com', messagePlaceholder: 'صف خطة نقلك باختصار' }, faq: { questions: ['كيف يتم حساب السعر؟', 'ماذا يحدث إذا تأخرت رحلتي؟', 'ما طرق الدفع المقبولة؟', 'كيف أختار السيارة؟'], answer: 'يقدم فريق الحجز معلومات واضحة بناءً على مسارك واحتياجاتك أثناء إعداد العرض.' }, footer: { description: 'نقل مريح وموثوق بعناية في قطر.', contact: 'اتصل بنا', contactText: 'ستضاف معلومات الهاتف وواتساب والبريد الإلكتروني هنا قريباً.', languages: 'اللغة', privacy: 'الخصوصية' },
  },
} as const

export type Translation = (typeof copy)[Language]
export function getTranslation(language: Language): Translation { return copy[language] }
export function formatMoney(value: number, language: Language): string { return new Intl.NumberFormat(language === 'ar' ? 'ar-QA' : language === 'en' ? 'en-QA' : 'tr-TR', { style: 'currency', currency: 'QAR', maximumFractionDigits: 2 }).format(value) }
export function formatDate(value: string | number | Date, language: Language): string { return new Intl.DateTimeFormat(language === 'ar' ? 'ar-QA' : language === 'en' ? 'en-GB' : 'tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
