import { ArrowRight, CarFront, Check, ChevronDown, Clock3, Globe2, Luggage, Menu, MessageCircle, Phone, Plane, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { getTranslation, type Language } from './lib/i18n'
import { db } from './lib/db'
import AdminPanel from './AdminPanel'
import BookingFlow from './BookingFlow'
import './booking-flow.css'

const images = ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85']
const icons = [Plane, CarFront, Sparkles, Users]
type Navigate = (to: string) => void

function App() {
  const [path, setPath] = useState(window.location.pathname || '/')
  const [menuOpen, setMenuOpen] = useState(false)
  const [language, setLanguage] = useState<Language>(() => { const saved = window.localStorage.getItem('vip-language'); return saved === 'en' || saved === 'ar' ? saved : 'tr' })
  const [selectedVehicle, setSelectedVehicle] = useState<string | undefined>(() => new URLSearchParams(window.location.search).get('vehicle') || undefined)
  const [routeSelection, setRouteSelection] = useState(() => { const params = new URLSearchParams(window.location.search); return { origin: params.get('origin') || undefined, destination: params.get('destination') || undefined } })
  const t = getTranslation(language)
  useEffect(() => { const onPop = () => { const params = new URLSearchParams(window.location.search); setPath(window.location.pathname || '/'); setSelectedVehicle(params.get('vehicle') || undefined); setRouteSelection({ origin: params.get('origin') || undefined, destination: params.get('destination') || undefined }) }; window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    window.localStorage.setItem('vip-language', language)
    const metadata: Record<string, [string, string]> = {
      '/': ['VIP Transfer | Katar özel şoförlü ulaşım', 'Katar\'da güvenli, konforlu ve zamanında VIP transfer ve şoförlü araç kiralama.'],
      '/hizmetler': ['VIP Transfer Hizmetleri | Katar', 'Havalimanı transferi, VIP şoförlü kiralama, etkinlik ve kurumsal ulaşım hizmetleri.'],
      '/filo': ['VIP Transfer Filosu | Katar', 'Katar yolculuklarınız için konforlu sedan, SUV ve VIP van seçeneklerini keşfedin.'],
      '/rezervasyon': ['Rezervasyon | VIP Transfer Katar', 'Bölgelerinizi, aracınızı ve ek hizmetlerinizi seçerek VIP transfer rezervasyonu oluşturun.'],
      '/kurumsal': ['Kurumsal Transfer | VIP Transfer Katar', 'Yönetici ve personel taşımacılığı için aylık anlaşmalı, düzenli VIP ulaşım.'],
      '/hakkimizda': ['Hakkımızda | VIP Transfer Katar', 'Dakik karşılama ve kişiye göre planlama ile Katar\'da güvenilir VIP transfer.'],
      '/sss': ['Sıkça Sorulan Sorular | VIP Transfer Katar', 'VIP transfer rezervasyonu, araçlar, fiyatlandırma ve hizmet bölgeleri hakkında yanıtlar.'],
      '/iletisim': ['İletişim | VIP Transfer Katar', 'VIP transfer planınız için VIP Transfer ekibiyle iletişime geçin.'],
      '/kvkk': ['Gizlilik ve KVKK | VIP Transfer Katar', 'VIP Transfer kişisel verilerin korunması ve gizlilik bilgilendirmesi.'],
    }
    const [title, description] = metadata[path] || metadata['/']
    document.title = language === 'en' ? title.replace('Katar', 'Qatar').replace('Hakkımızda', 'About us') : language === 'ar' ? 'VIP Transfer | نقل فاخر في قطر' : title
    let descriptionNode = document.head.querySelector<HTMLMetaElement>('meta[name="description"]')
    if (!descriptionNode) { descriptionNode = document.createElement('meta'); descriptionNode.name = 'description'; document.head.appendChild(descriptionNode) }
    descriptionNode.content = description
    let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]')
    if (!canonical) { canonical = document.createElement('link'); canonical.rel = 'canonical'; document.head.appendChild(canonical) }
    canonical.href = `${window.location.origin}${path}`
    let schema = document.head.querySelector<HTMLScriptElement>('script[data-vip-schema]')
    if (!schema) { schema = document.createElement('script'); schema.type = 'application/ld+json'; schema.dataset.vipSchema = 'true'; document.head.appendChild(schema) }
    schema.textContent = JSON.stringify({ '@context': 'https://schema.org', '@graph': [{ '@type': 'LocalBusiness', '@id': `${window.location.origin}/#business`, name: 'VIP Transfer', areaServed: 'Qatar', url: window.location.origin, priceRange: '$$', serviceType: 'VIP transfer and chauffeured vehicle rental' }, { '@type': 'Service', serviceType: 'VIP transfer', provider: { '@id': `${window.location.origin}/#business` }, areaServed: 'Qatar', url: `${window.location.origin}${path}` }] })
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [path, language])
  const navigate: Navigate = (to) => { const params = new URLSearchParams(to.split('?')[1] || ''); window.history.pushState({}, '', to); setPath(to.split('?')[0]); setSelectedVehicle(params.get('vehicle') || undefined); setRouteSelection({ origin: params.get('origin') || undefined, destination: params.get('destination') || undefined }); setMenuOpen(false) }
  if (path === '/admin') return <AdminPanel />
  return <div className="site-shell"><a className="skip-link" href="#main-content">{language === 'ar' ? 'تخطي إلى المحتوى' : language === 'en' ? 'Skip to content' : 'İçeriğe geç'}</a><Header path={path} menuOpen={menuOpen} setMenuOpen={setMenuOpen} navigate={navigate} language={language} setLanguage={setLanguage} /><main id="main-content">{path === '/' ? <Home navigate={navigate} language={language} /> : <Page path={path} navigate={navigate} selectedVehicle={selectedVehicle} routeSelection={routeSelection} language={language} />}</main><Footer navigate={navigate} language={language} /><div className="mobile-bar"><a href="/iletisim" onClick={(e) => { e.preventDefault(); navigate('/iletisim') }}><Phone size={18} />{t.actions.call}</a><a href="/iletisim" onClick={(e) => { e.preventDefault(); navigate('/iletisim') }}><MessageCircle size={18} />{t.actions.whatsapp}</a></div></div>
}

function Header({ path, menuOpen, setMenuOpen, navigate, language, setLanguage }: { path: string; menuOpen: boolean; setMenuOpen: (v: boolean) => void; navigate: Navigate; language: Language; setLanguage: (v: Language) => void }) {
  const t = getTranslation(language); const navItems = [[t.nav.services, '/hizmetler'], [t.nav.fleet, '/filo'], [t.nav.corporate, '/kurumsal'], [t.nav.about, '/hakkimizda'], [t.nav.faq, '/sss'], [t.nav.contact, '/iletisim'], [t.nav.booking, '/rezervasyon']]
  return <header className="site-header"><button className="wordmark" onClick={() => navigate('/')} aria-label={t.labels.home}><span>VIP</span> TRANSFER</button><button className="menu-toggle" aria-label={menuOpen ? t.labels.menuClose : t.labels.menuOpen} aria-expanded={menuOpen} aria-controls="primary-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button><nav id="primary-navigation" className={menuOpen ? 'nav nav-open' : 'nav'} aria-label={t.nav.services}>{navItems.map(([label, href]) => <a key={href} aria-current={path === href ? 'page' : undefined} href={href} onClick={(e) => { e.preventDefault(); navigate(href) }}>{label}</a>)}<label className="language-select"><Globe2 size={15} /><span className="sr-only">{t.labels.language}</span><select value={language} onChange={(e) => setLanguage(e.target.value as Language)} aria-label={t.labels.language}><option value="tr">TR</option><option value="en">EN</option><option value="ar">AR</option></select></label><a className="nav-cta" href="/rezervasyon" onClick={(e) => { e.preventDefault(); navigate('/rezervasyon') }}>{t.actions.quote} <ArrowRight size={16} /></a></nav></header>
}

function Home({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); return <><section className="hero section-wrap"><div className="hero-copy"><p className="eyebrow">{t.home.eyebrow}</p><h1>{t.home.title}</h1><p className="hero-text">{t.home.intro}</p><RoutePlanner navigate={navigate} language={language} /><div className="hero-actions"><a className="text-link" href="/hizmetler" onClick={(e) => { e.preventDefault(); navigate('/hizmetler') }}>{t.actions.explore}</a></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=85" alt={language === 'ar' ? 'سيارة فاخرة أمام أضواء المدينة' : language === 'en' ? 'Luxury vehicle in city lights' : 'Gece şehir ışıkları önünde lüks araç'} /><div className="hero-note"><span className="note-dot" /> {language === 'ar' ? 'اهتمام شخصي في كل رحلة' : language === 'en' ? 'Personal care on every journey' : 'Her yolculukta kişisel ilgi'}</div></div></section><TrustStrip language={language} /><section className="section-wrap section"><SectionHeading eyebrow={t.home.servicesEyebrow} title={t.home.servicesTitle} text={t.home.servicesText} /><ServiceGrid navigate={navigate} language={language} /></section><section className="fleet-band"><div className="section-wrap section"><SectionHeading eyebrow={t.home.fleetEyebrow} title={t.home.fleetTitle} text={t.home.fleetText} /><FleetGrid navigate={navigate} language={language} /></div></section><section className="section-wrap section two-column"><div><p className="eyebrow">{t.home.whyEyebrow}</p><h2>{t.home.whyTitle}</h2></div><div className="benefits"><Benefit icon={<Users size={21} />} title={language === 'ar' ? 'مصمم لك' : language === 'en' ? 'Planned for you' : 'Size göre planlanır'} text={language === 'ar' ? 'نختار السيارة والمسار المناسبين لعدد الركاب والحقائب والبرنامج.' : language === 'en' ? 'We shape the right vehicle and route around your passengers, luggage and schedule.' : 'Güzergâhınız, bagajınız ve programınız için doğru araç ve akışı birlikte kurgularız.'} /><Benefit icon={<Luggage size={21} />} title={language === 'ar' ? 'نحن نهتم بالتفاصيل' : language === 'en' ? 'Details are covered' : 'Detaylar bizde'} text={language === 'ar' ? 'من لوحة الاستقبال إلى وقت الانتظار، نهتم بكل خطوة.' : language === 'en' ? 'From welcome signs to waiting time, every step is considered.' : 'Karşılama tabelasından bekleme süresine kadar yolculuğun her adımı düşünülür.'} /></div></section><BookingBand navigate={navigate} language={language} /></> }

function RoutePlanner({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); const [zones, setZones] = useState<Array<{ id: string; name: string }>>([]); const [origin, setOrigin] = useState(''); const [destination, setDestination] = useState(''); useEffect(() => { let active = true; db.select<{ id: string; name: string }>('zones', { filters: { is_active: true }, orderBy: 'name' }).then(rows => { if (active) setZones(rows) }).catch(() => { if (active) setZones([]) }); return () => { active = false } }, []); return <form className="route-planner" onSubmit={(e) => { e.preventDefault(); if (origin && destination && origin !== destination) navigate(`/rezervasyon?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}`) }}><div className="planner-grid"><label>{t.labels.service}<select defaultValue="airport_transfer"><option value="airport_transfer">{t.home.airport}</option><option value="chauffeured_rental">{t.home.rental}</option><option value="corporate_transfer">{t.home.corporate}</option></select></label><label>{t.labels.from}<select required value={origin} onChange={e => setOrigin(e.target.value)}><option value="">{t.home.origin}</option>{zones.map(zone => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label>{t.labels.to}<select required value={destination} onChange={e => setDestination(e.target.value)}><option value="">{t.home.destination}</option>{zones.map(zone => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label></div><button className="button button-primary" type="submit">{t.actions.route} <ArrowRight size={17} /></button></form> }
function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: ReactNode; text: string }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{text}</p></div> }
function TrustStrip({ language }: { language: Language }) { return <section className="trust-strip section-wrap" aria-label="Trust signals">{getTranslation(language).home.trust.map((item, i) => <div key={item}>{(() => { const Icon = [ShieldCheck, Clock3, Sparkles][i]; return <Icon size={20} /> })()}<span>{item}</span></div>)}</section> }
function ServiceGrid({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); return <div className="service-grid">{t.services.map(({ title, text }, index) => { const Icon = icons[index]; return <article className={index === 1 ? 'service-card service-card-dark' : 'service-card'} key={title}><Icon size={22} /><span className="card-index">0{index + 1}</span><h3>{title}</h3><p>{text}</p><button className="inline-action" onClick={() => navigate('/rezervasyon')}>{t.actions.quote} <ArrowRight size={16} /></button></article> })}</div> }
function FleetGrid({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); const names = ['Executive Van', 'Luxury Sedan', 'Premium SUV']; return <div className="fleet-grid">{t.fleet.map((car, i) => <article className="fleet-card" key={names[i]}><img src={images[i]} alt={car.alt} loading="lazy" /><div className="fleet-info"><div><h3>{names[i]}</h3><p>{car.meta}</p><small>{car.equipment}</small></div><button onClick={() => navigate(`/rezervasyon?vehicle=${encodeURIComponent(names[i])}`)} aria-label={`${names[i]} — ${t.actions.quote}`}><ArrowRight size={20} /></button></div></article>)}</div> }
function Button({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="button button-primary" onClick={onClick}>{children} <ArrowRight size={17} /></button> }
function BookingBand({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); return <section className="booking section-wrap"><div className="booking-inner"><p className="eyebrow">{t.home.bookingEyebrow}</p><h2>{t.home.bookingTitle}</h2><p>{t.home.bookingText}</p><Button onClick={() => navigate('/rezervasyon')}>{t.actions.start}</Button></div></section> }
function Benefit({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div>{icon}<h3>{title}</h3><p>{text}</p></div> }

function Page({ path, navigate, selectedVehicle, routeSelection, language }: { path: string; navigate: Navigate; selectedVehicle?: string; routeSelection: { origin?: string; destination?: string }; language: Language }) { const t = getTranslation(language); const key = ({ '/hizmetler': 'services', '/filo': 'fleet', '/kurumsal': 'corporate', '/hakkimizda': 'about', '/iletisim': 'contact', '/kvkk': 'kvkk', '/sss': 'faq', '/rezervasyon': 'booking' } as Record<string, keyof typeof t.pages>)[path] || 'services'; const current = t.pages[key]; return <><section className="page-hero"><div className="section-wrap"><p className="eyebrow">{current[0]}</p><h1>{current[1]}</h1><p className="hero-text">{current[2]}</p></div></section><section className="section-wrap section page-content">{path === '/hizmetler' && <ServiceGrid navigate={navigate} language={language} />}{path === '/filo' && <FleetGrid navigate={navigate} language={language} />}{path === '/rezervasyon' && <BookingFlow language={language} selectedVehicle={selectedVehicle} initialRoute={routeSelection} />}{path === '/sss' && <Faq language={language} />}{path === '/iletisim' && <Contact navigate={navigate} language={language} />}{path === '/kvkk' && <Legal language={language} />}{path === '/kurumsal' && <Corporate language={language} />}{path === '/hakkimizda' && <About language={language} />}</section></> }
function ReservationSteps({ selectedVehicle, language }: { selectedVehicle?: string; language: Language }) { const t = getTranslation(language); return <div className="steps-grid">{t.booking.steps.map((step, i) => <article className="step-card" key={step}><span>0{i + 1}</span><Check size={18} /><h3>{step}</h3><p>{t.booking.details[i]}</p>{i === 1 && selectedVehicle && <small className="selected-vehicle">{t.booking.selected}: {selectedVehicle}</small>}</article>)}</div> }
function Faq({ language }: { language: Language }) { const t = getTranslation(language); return <div className="faq-list">{t.faq.questions.map((q) => <details key={q}><summary>{q}<ChevronDown size={18} /></summary><p>{t.faq.answer}</p></details>)}</div> }
function Contact({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); return <div className="contact-layout"><div className="contact-note"><h2>{t.contact.title}</h2><p>{t.contact.text}</p><Button onClick={() => navigate('/rezervasyon')}>{t.actions.plan}</Button></div><form className="contact-form" onSubmit={(e) => { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); const honeypot = String(data.get('website') || ''); if (honeypot || !form.checkValidity()) { form.reportValidity(); return } }}><label>{t.labels.name}<input required name="name" autoComplete="name" placeholder={t.contact.namePlaceholder} /></label><label>{t.labels.email}<input required type="email" name="email" autoComplete="email" placeholder={t.contact.emailPlaceholder} /></label><label>{t.labels.message}<textarea required name="message" rows={5} placeholder={t.contact.messagePlaceholder} /></label><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" name="website" /></label><button className="button button-primary" type="submit">{t.actions.send} <ArrowRight size={17} /></button></form></div> }
function Corporate({ language }: { language: Language }) { return <div className="copy-grid"><h2>{language === 'ar' ? <>في كل اجتماع<br /><em>في الموعد.</em></> : language === 'en' ? <>On time<br /><em>for every meeting.</em></> : <>Her toplantıya<br /><em>zamanında.</em></>}</h2><div><p>{language === 'ar' ? 'ندير نقل الموظفين والمديرين باتفاقيات شهرية وتقارير منتظمة وعمليات مفوترة.' : language === 'en' ? 'We manage employee and executive transfers with monthly agreements, regular reporting and invoiced operations.' : 'Kurumsal personel taşıma ve yönetici transferlerini aylık anlaşma, düzenli raporlama ve faturalı operasyonla yönetiyoruz.'}</p></div></div> }
function About({ language }: { language: Language }) { const t = getTranslation(language); return <div className="copy-grid"><h2>{language === 'ar' ? <>الراحة<br /><em>معيارنا.</em></> : language === 'en' ? <>Comfort is<br /><em>our standard.</em></> : <>Konforu standart<br /><em>kabul ediyoruz.</em></>}</h2><div><p>{t.pages.about[2]}</p><ul className="check-list"><li><Check size={17} /> {language === 'ar' ? 'استقبال دقيق' : language === 'en' ? 'Punctual pickup' : 'Dakik karşılama'}</li><li><Check size={17} /> {language === 'ar' ? 'تخطيط حسب احتياجك' : language === 'en' ? 'Personal planning' : 'Kişiye göre planlama'}</li></ul></div></div> }
function Legal({ language }: { language: Language }) { return <div className="legal-copy"><h2>{language === 'ar' ? 'بيان الخصوصية' : language === 'en' ? 'Privacy notice' : 'Aydınlatma metni'}</h2><p>{language === 'ar' ? 'تُستخدم المعلومات التي تتم مشاركتها عبر نموذج التواصل للرد على طلبك وإدارة الحجز فقط.' : language === 'en' ? 'Information shared through the contact form is used only to answer your request and manage the reservation process.' : 'İletişim formu üzerinden paylaşılan bilgiler yalnızca talebinizi yanıtlamak ve rezervasyon sürecini yürütmek amacıyla işlenir.'}</p></div> }
function Footer({ navigate, language }: { navigate: Navigate; language: Language }) { const t = getTranslation(language); return <footer className="site-footer"><div className="section-wrap footer-grid"><div><button className="wordmark" onClick={() => navigate('/')}><span>VIP</span> TRANSFER</button><p>{t.footer.description}</p></div><div><p className="eyebrow">{t.footer.contact}</p><p>{t.footer.contactText}</p></div><div><p className="eyebrow">{t.footer.languages}</p><p>Türkçe · English · العربية</p></div></div><div className="section-wrap footer-bottom"><span>© 2026 VIP Transfer</span><button onClick={() => navigate('/kvkk')}>{t.footer.privacy}</button></div></footer> }

export default App
